name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: mac setup
      run: brew install automake
      if: runner.os == 'macOS'
    - name: setup
      run: ./am_setup
    - name: configure
      run: ./configure
    - name: make
      run: make
